### ISSUE TITLE
Provide a way to clean up Gen'd values

### ISSUE THREAD

**Issue by iphydf** [scalameter/scalameter#114]
In my tests, I need to create expensive objects from a scarce resource. The creation and the destruction both take a non-trivial amount of time, so when feasible, I moved the construction part out of the test and into a generator.

The problem now is that for benchmarking, many of those objects will be created, and I run out. I temporarily solved it with a simple retry-after-GC thing, but it's suboptimal. Some benchmarks cause the object to allocate a lot of native memory, so I run out of that, as well. Calling close() on it releases that.

The simplest solution I can see would be to call close() on Closeable and AutoCloseable (if !preJDK7) objects produced by Gens once they are disposed of by the framework.

**Comment by axel22** [comment]
Did you take a look at the cached generator:

https://scalameter.github.io/home/gettingstarted/0.7/generators/

Would that help?

**Comment by axel22** [comment]
Also, would using `setUp` and `tearDown` methods help?

Looks like we did not expose them on the [`japi` frontend](https://github.com/scalameter/scalameter/blob/master/src/main/scala/org/scalameter/japi/Using.java). This needs to be done for the next release. Feel free to address this, otherwise I will do it for the next release eventually.

**Comment by axel22** [comment]
Btw, a temporary workaround if the lack of `tearDown` in `japi` is a problem, would possibly be to have generators allocate the required memory, and call `close` at the end of the snippet. This is assuming that calling `close` does not significantly affect the benchmark.

**Comment by iphydf** [comment]
`close` is a potentially expensive operation. It does a bunch of bookkeeping on the native side. With a high enough iteration count, it becomes negligible, so it's enough as temporary workaround.

The cached generator helps for cacheable instances (ones I don't mutate in the benchmarks). It's a bit slower than my own caching with `immutable.HashMap`: 1min, 22s using the hashmap, 1min, 37s using `Gen.cached`. It also takes more memory: 2.3G RES for the hashmap, 2.7G for cached gen.

When would those `setUp` and `tearDown` methods be called? When are the generated values actually dropped on the floor? Evidently even uncached generators are not called for every test run, so it's hard to decide when it's safe to close an instance. Oh, that brings me to a reason why calling `close()` inside the benchmark won't work: it will make subsequent benchmarks fail. I consider that to be a bug. Report for that coming soon :).

**Comment by axel22** [comment]
The `setUp` function is called before every invocation of the snippet, and `tearDown` is called after every invocation of the snippet.

The `beforeTests` and `afterTests` are invoked before and after all the tests, respectively (see [here](https://github.com/axel22/scalameter/blob/c1daf8e1d8d4d41258d20662b59fdb111af6deb2/src/test/scala/org/scalameter/examples/BeforeAfterTest.scala)).

The references to generated values are released when a new value is instantiated by the `Measurer`, which can be controlled with `Key.exec.reinstantiation.frequency`.

**Comment by axel22** [comment]
The values for the cached generators are created only once (per JVM instance), and reused throughout the benchmark.

**Comment by iphydf** [comment]
My problem is more or less solved by using `setUp` and `.cached`. I have no strong desire for hooking into the instantiation and cleanup, anymore, so if you feel this feature is not useful, feel free to close the bug.
