### ISSUE TITLE
Non-cached generators should be called for fresh values on each test run

### ISSUE THREAD

**Issue by iphydf** [scalameter/scalameter#116]
This code should not throw an AssertionError:
```
var nextInt = 0
val getInt = (_: Unit) => {
  nextInt += 1
  nextInt
}

var numbersSeen: List[Int] = Nil

performance of "List.contains" in {
  using(Gen.unit("axis") map getInt) in { number =>
    assert(!numbersSeen.contains(number))
    numbersSeen = number :: numbersSeen
  }
}
```

**Comment by axel22** [comment]
If you are modifying global state outside the snippet body, you must take care to reset that state using `setUp` or `tearDown`, as any snippet can be potentially invoked more than once. Example of using `tearDown` is here:

https://github.com/scalameter/scalameter/blob/master/src/test/scala/org/scalameter/collections/SetBenchmarks.scala#L139

Note that the invoking the snippet does not mean that a new value is generated by the generator. This depends on the measurer and its configuration. If you really want this, you could set the reinstantiation frequency to `1`:

https://github.com/scalameter/scalameter/blob/master/scalameter-core/src/main/scala/org/scalameter/keys.scala#L120

**Comment by iphydf** [comment]
I see. My code snippet didn't quite convey the point I was trying to make, though I understand why it happens now.

Is it possible to pre-process the value each time it goes into the test? I'm testing "adding friends to the friend list" on a mutable object, and my test requires me to either set reinstantiation frequency to 1 or instantiate it inside the test, skewing the results a little. I would actually prefer not to instantiate so many of these objects without the ability to `close()` them. If it were possible to clear the friend list before running the test, that would solve the problem.

In fact, the reinstantiation frequency probably solves the problem, as I can configure those specific tests to do that, and set the frequency to something very high by default. I'll try that.

What I want to test is: how long does it take to add 1000, 2000, 3000, etc. friends to an empty friend list?

**Comment by axel22** [comment]
You would need to use `setUp`, like this:

    using(genOfListAndInt) curve("curve name") tearDown {
        case (friendList, num) => friendList.clear()
      } in { case (friendList, num) =>
        // add num friends to friendList
      }

**Comment by iphydf** [comment]
This works. Combined with a high `exec.reinstantiation.frequency` (bad name, setting it to high values actually means low frequency), I get acceptable test results. Unfortunately, clearing the friend list is a linear operation (because this is not something people usually do, so there is no method for it and I need to iterate over the friend list, deleting each one).

Setting reinstantiation frequency to 1 doesn't work, because the warmup run still uses the same value several times, so I still need to clear the friend list.

**Comment by axel22** [comment]
You might want to set the `Warmer` to [`Warmer.Zero`](https://github.com/scalameter/scalameter/blob/master/scalameter-core/src/main/scala/org/scalameter/Warmer.scala#L21), which avoids warming altogether.

Otherwise, if warming is needed, a workaround is to implement your own warmer.
For the next release, we could address the problem by introducing a warmer key that specifies reinstantiation frequency.

**Comment by iphydf** [comment]
Thanks, warming is not needed for this test. I'll have to wait for the next 0.7-SNAPSHOT, because overriding warmer is not possible right now (see #115).

**Comment by axel22** [comment]
The snapshot should have been released automatically after the commit:

https://travis-ci.org/scalameter/scalameter/jobs/65764380

JFYI: implementing a `PerformanceTest` is an alternative for custom `Measurer`s in `0.6`.
