### ISSUE TITLE
Can't download the latest 0.7-SNAPSHOT

### ISSUE THREAD

**Issue by iphydf** [scalameter/scalameter#118]
```
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/storm-enroute/scalameter_2.11/0.7-SNAPSHOT/scalameter_2.11-0.7-SNAPSHOT.jar ...
[warn]  [FAILED     ] com.storm-enroute#scalameter_2.11;0.7-SNAPSHOT!scalameter_2.11.jar: invalid sha1: expected=b9990c9b697f02c8b34d1a8d1aa8c7c9552897d9 computed=adfb28fdf5253b1b1191d1749884c0e204b0f25e (2472ms)
```

This happens both on my local machine and on [travis](https://travis-ci.org/iphydf/tox4j/jobs/66142356#L4514). This blocks me from doing any tests whatsoever unless I delete all scalameter tests and remove it from build.sbt.

**Comment by axel22** [comment]
Weird, the `0.7-SNAPSHOT` version can be found here:

https://oss.sonatype.org/#nexus-search;quick~scalameter

Investigating...

**Comment by axel22** [comment]
Seems to work now:

https://travis-ci.org/scalameter/scalameter-examples/jobs/64837094

This might be somehow related to the recent Sonatype outage:

http://status.sonatype.com/
