### ISSUE TITLE
Parameter(axis) in HTML report

### ISSUE THREAD

**Issue by iphydf** [scalameter/scalameter#124]
Since the new pickler API, axes in the html report previously called "axis" are now called "Parameter(axis)". As a result, I am no longer able to open the "friends" axis, because the draggable axis label reaches beyond the ">" used to open it.

![20150621221347](https://cloud.githubusercontent.com/assets/10647936/8273383/d2ad3002-1862-11e5-8ac5-1bbfb523a1eb.jpg)

**Comment by axel22** [comment]
Thanks for reporting this so quickly

@kjanosz 
We could either fix the `toString` method in `Parameter`, or we could fix the `HTMLReporter`. I'd say we should do both, as it would make `HTMLReporter` more robust in the future.
