### ISSUE TITLE
Exception when using SeparateJvmsExecutor with verbose key set to false.

### ISSUE THREAD

**Issue by kjanosz** [scalameter/scalameter#136]
(I'm rewriting the [last comment](https://github.com/scalameter/scalameter/pull/135#issuecomment-119372182) from #135) 

I've encountered into some strange behaviour when spawning new JVM with default `jvmflags` (`"-Xmx2048m -Xms2048m -XX:CompileThreshold=100"`)

```
Error: Could not find or load main class  -Xmx2048m -Xms2048m -XX:CompileThreshold=100
```
Note the extra space before `-Xmx2048m`.

Changing line 27 in `SeparateJvmsExecutor` from:
`val flags = s"${if (currentContext(Key.verbose)) "-verbose:gc " else ""}" + existingFlags`
to:
`val flags = s"${if (currentContext(Key.verbose)) "-verbose:gc" else ""} " + existingFlags`
changes only error msg:
```
Invalid maximum heap size: -Xmx2048m -Xms2048m -XX:CompileThreshold=100
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit
```

**Comment by kjanosz** [comment]
@axel22: I've done some quickfix and changing `jvmflags` key type from `String` to `List[String]` works. Alternatively splitting over `jvmflags` before creation of commands sequence in `JvmRunner.runJvm` should work to, but won't it break usages when any of flags contain whitepsace? (don't know if this is allowed behaviour)

**Comment by axel22** [comment]
It sounds as if the multiple command-line arguments were merged into a single argument. This could be related to the recent [whitespace-related refactoring](https://github.com/scalameter/scalameter/issues/93).

About `List[String]` - yes, please! :)
