### ISSUE TITLE
Warmup.Zero with SeparateJvmsExecutor throws an exception

### ISSUE THREAD

**Issue by mdedetrich** [scalameter/scalameter#143]
It seems that `Warmup.Zero` has no serializer for Java, which means that it throws an exception if you try to run it with a `SeparateJvmsExecutor`, this is the stack trace that I get

https://gist.github.com/mdedetrich/575f9a9a003acb6c437f

We are trying to test how effective the `@inline`, hence why we are setting `Warmup.Zero` and running it in separate JVM's

**Comment by axel22** [comment]
The `Warmup.Zero` is a `case object`, so it is serializable. Trouble is, the `Foreach` class instance that its implementation captures happens to be declared as non-Serializable.

Should be fixed by:

https://github.com/scalameter/scalameter/commit/5ccf6d45d0a5f8cdf9c1bfa24a4f0a0fbea0cd37

**Comment by axel22** [comment]
Just be aware that you should use `Warmer.Zero` only for non-running-time-related benchmarks.

Even if the `@inline` annotation does its job, the results of the bench will be inconclusive, since it takes some time for the JVM to optimize/translate to machine code whatever code it is you are testing.

**Comment by mdedetrich** [comment]
@axel22 Do you know if its possible to use `scalameter` to measure the effect of JVM JIT/warmup. We are just trying to get an estimated guess of whether our use of `@inline` is worth it.

What I was planning to do is to run the test specifically on a separate `JVM` instance (so you can actually measure before it fully warms up)

**Comment by axel22** [comment]
I guess you could try it out to see how stable the measurements are.
You would have to set the warmup to zero as you did, and set `benchRuns` and `independentSamples` to N, where N is the number of times you want to measure this.
Finally, you would have to set the running time `Measurer` to `Measurer.Default` (the default one does not repeat measurements in case of GC, or eliminate outliers).

**Comment by axel22** [comment]
How stable the results are will depend a lot on what exactly the benchmark is.

**Comment by mdedetrich** [comment]
Yeah that was pretty much what I was planning to do, the issue we hit was when we tried to run the benchmarks on separate VM's. I assume you should still do this to be more accurate?

**Comment by axel22** [comment]
Yes, if you want to measure the warmup time, then you'd have to start a new VM, so SeparateJvmExecutor should do the job.
The 0.7-SNAPSHOT should contain the fix.

On July 26, 2015 11:24:18 AM GMT+02:00, Matthew de Detrich <notifications@github.com> wrote:
>Yeah that was pretty much what I was planning to do, the issue we hit
>was when we tried to run the benchmarks on separate VM's. I assume you
>should still do this to be more accurate?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/scalameter/scalameter/issues/143#issuecomment-124963473

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mdedetrich** [comment]
Cheers, thanks for the help!
