### ISSUE TITLE
Accuracy when using with scala-offheap/unsafe

### ISSUE THREAD

**Issue by mdedetrich** [scalameter/scalameter#161]
Scala-meter does its best to try and account for GC sweeps to provide accurate results for benchmarking, however if you are using stuff like `scala-offheap` or `sun.misc.unsafe` to allocate memory off the heap, these won't incur GC costs.

Would using scalameter to compare scala-offheap to non scala offheap be a like for like comparison, or will the comparison not be legitimate because scala-offheap tries to remove the cost of GC in its benchmark results

**Comment by axel22** [comment]
If you want to compare normal Scala programs to scala-offheap programs and take GC costs into account, then you should override the `measurer` method to return `new Measurer.Default` or `new Measurer.Default with Measurer.PeriodicReinstantiation`, and increase the number of runs until you notice that the measurements are stable.

If you want to ignore the costs of GC in normal Scala programs, then just use the default measurers.

**Comment by mdedetrich** [comment]
Cheers thanks.

Actually due to this, I have verified that I wasn't even using offheap properly (I was wondering why there wasn't a difference in measurements)
