### ISSUE TITLE
Share state between different runs

### ISSUE THREAD

**Issue by jarandaf** [scalameter/scalameter#165]
Hi there,

I wonder if sharing state between different runs (for non-parallel tests) is possible. The use case I have come up with is I require to load some files (which depend on defined generators) from which I initialize some sort of state which is modified throghout different measures later on.

The following is a simplified example of what I am trying to accomplish:

```scala
object FooBenchmark extends Bench.OfflineReport {
  val ns = List(1,2)
  val ks = List(3,4)
  val nGen : Gen[Int] = Gen.enumeration("n")(ns: _*)
  val kGen : Gen[Int] = Gen.enumeration("k")(ks: _*)
  val myGen : Gen[(Int, Int)] = for {
    n <- nGen
    k <- kGen
  } yield (n,k)

  // Mutable hashmap used to store some data extracted from input files
  var data = HashMap[String, Set[Baz]]

  performance of "foo" config (
    exec.benchRuns -> 10
  ) in {
    using(myGen) beforeTests {
      // Load required files (loadFile mutates data variable)
      for {
        n <- ns
        k <- ks
      } yield loadFile(n,k)
    } in {
      case (n,k) => {
        measure method "bar" in { 
          // corresponding data file is used here 
        }
      }
    }
  }
} 
```

With the above version, all files are loaded repeatedly (I'm still not sure how many times; when are `beforeTests` blocks actually executed?). I have checked the current DSL and it seems it is not supported. It might be interesting to differentiate between blocks to be executed before all generator values are consumed (i.e. before each run) and blocks to be executed before all benchmark runs are executed (with state).

**Comment by axel22** [comment]
You should create a transient field in the enclosing object and initialize
it from `beforeTests` if it is `null`.

**Comment by axel22** [comment]
~~You should create a transient field in the enclosing object and initialize
it from `beforeTests` if it is `null`.~~ I mistook the meaning of `beforeTests` for `setUp`.

The answer is that if you run all your tests in the same JVM (controlled by the `independentSamples` configuration parameter), then `beforeTests` should run only once. However, if you run multiple VMs, then there is no way to persist memory state between them, in general.

**Comment by jarandaf** [comment]
How does `independentSamples` parameter actually work? Sorry, I was not able to find the actual meaning of all configuration keys. Does it mean that all generator value measures are run in different JVM's (up to `independentSamples`) in parallel? Would this imply that setting `indepententSamples` to 1 slows down the benchmark execution time?

**Comment by axel22** [comment]
Hi,

Sorry for the silence! If you use the SeparateJvmExecutor (which is used by
OfflineReport unless you override it), then execution is broken down into
several runs of independent JVM (the assumption is that this will give a
better average compared to running everything in one JVM run). To disable
this, set that parameter to 1.

Cheers,
Alex

**Comment by jarandaf** [comment]
Thank you for your answer @axel22, I'm closing this issue.
