### ISSUE TITLE
publish for Scala 2.12?

### ISSUE THREAD

**Issue by SethTisue** [scalameter/scalameter#169]
I see build support for 2.12.0-M1, but nothing more recent. will you be publishing for 2.12.0-RC1?

**Comment by axel22** [comment]
I guess it could be - let me check if all the dependencies are available for RC1.

**Comment by SethTisue** [comment]
see https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md

**Comment by axel22** [comment]
Thanks! I think we're blocked on `casbah` at the moment, but I could cheat and try to use 2.11 version.

**Comment by SethTisue** [comment]
You might let them know at https://github.com/mongodb/casbah/pull/85.

It's exceedingly unlikely that using any 2.11 libraries from 2.12 will work.

**Comment by axel22** [comment]
It should be ok, though, since `casbah` is related to a newly added feature anyway, which alone then just won't work.

https://github.com/scalameter/scalameter/commit/d81c9627685260b01f8dc335d008bd141bdf9ae4

I published this change as the `0.8` version of ScalaMeter, Scala 2.12.0-RC1.

**Comment by axel22** [comment]
I re-published with version `0.8.1`, since `0.8` has some invalid dependencies.

**Comment by SethTisue** [comment]
great! added 0.8.1 to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md
