### ISSUE TITLE
Scala 2.12 compatibility

### ISSUE THREAD

**Issue by ctongfei** [scalameter/scalameter#171]
Please build and release a Scala 2.12-compatible version of Scalameter :-)

**Comment by axel22** [comment]
There is one for Scala 2.12.0-RC1 - does that work for you?

**Comment by ctongfei** [comment]
Scala 2.12.0 (official release, http://get-scala.org/2.12) is out. 2.12.0 is not binary compatible with 2.12.0-RC1.

**Comment by axel22** [comment]
Thanks for the heads up!

It looks like we are currently blocked on:

http://central.maven.org/maven2/com/fasterxml/jackson/module/

The Jackson module for Scala published only 2.12.0-RC1.

**Comment by axel22** [comment]
I've opened an issue: https://github.com/FasterXML/jackson-module-scala/issues/295

**Comment by axel22** [comment]
Casbah is also a blocker:

https://mvnrepository.com/artifact/org.mongodb/casbah_2.12.0-RC1/3.1.1

http://central.maven.org/maven2/org/mongodb/

**Comment by ctongfei** [comment]
Thanks!

**Comment by axel22** [comment]
0.8.2 version for Scala 2.12 is released on Sonatype and on its way to Maven central.

**Comment by maxcom** [comment]
Please release 0.8.2 for 2.11 and 2.10 too. We are doing cross-build for different versions of Scala and it would be easier to have the same version of scalameter for all builds.

**Comment by axel22** [comment]
Done - published for 2.10 and 2.11.

**Comment by maxcom** [comment]
Thank you.

10 Ноя 2016 г. 20:09 пользователь "Aleksandar Prokopec" <
notifications@github.com> написал:
