### ISSUE TITLE
Comparison with JMH?

### ISSUE THREAD

**Issue by Petikoch** [scalameter/scalameter#173]
One of the most popular tools for benchmarks on the JVM is JMH
http://openjdk.java.net/projects/code-tools/jmh/

Is there somewhere some kind of comparison? 
For those people coming from JMH? 
Why choose ScalaMeter? 
...

:-)

Best regards,
Peti

**Comment by DarkDimius** [comment]
See discussion here: https://github.com/scala/collection-strawman/pull/19#discussion_r96680720

**Comment by Petikoch** [comment]
Thanks a lot @DarkDimius for the link, now I understand much better the difference.
