### ISSUE TITLE
Wrong type for `org.mongodb:casbah_2.11` dependency in Maven

### ISSUE THREAD

**Issue by aalexandrov** [scalameter/scalameter#176]
[The `pom.xml`](http://repo1.maven.org/maven2/org/mongodb/casbah_2.11/3.1.1/casbah_2.11-3.1.1.pom) lists `org.mongodb:casbah-commons_2.11::3.1.1` without explicitly specifying the dependency type as `pom` (default is `jar`).

Consequently, adding `scalameter` to a Maven project like this

```xml
<!-- Scalameter -->
<dependency>
    <groupId>com.storm-enroute</groupId>
    <artifactId>scalameter_2.11</artifactId>
    <version>0.8.2</version>
</dependency>
```

fails on `mvn dependency:resolve` with the following error:

> Could not resolve dependencies for project org.emmalanguage:emma-rt:jar:0.2-SNAPSHOT: Could not find artifact org.mongodb:casbah_2.11:jar:3.1.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

The following workaround works for me:

```xml
<!-- Scalameter -->
<dependency>
    <groupId>com.storm-enroute</groupId>
    <artifactId>scalameter_2.11</artifactId>
    <version>0.8.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.mongodb</groupId>
            <artifactId>casbah_2.11</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>casbah_2.11</artifactId>
    <version>3.1.1</version>
    <type>pom</type>
</dependency>
```

However, I think that the issue can be somehow resolved in the SBT config.

**Comment by axel22** [comment]
Thanks! Fixed in: https://github.com/scalameter/scalameter.github.com/commit/e0e7abf52753a92cdbd646c2f9ccc83bac2842ab
