### ISSUE TITLE
`HtmlReporter` copies first `index.html` found on classpath instead of correct one

### ISSUE THREAD

**Issue by zegerhoogeboom** [scalameter/scalameter#182]
The `HtmlReporter` currently copies the first `index.html` found on the classpath. This is done on line 151: `val res = getClass.getClassLoader.getResourceAsStream(from)`. This means that when there are multiple `index.html` files on the classpath, which is mainly caused by loading multiple JAR's which _also_ contain an `index.html` file. I guess the same goes for the other static files in `css/*` etc. In my case this cause another `index.html` to be loaded and thus I could not view the results. 

I did a very dirty quick fix by just copying the `HtmlReporter` in a class of my own and updating the loading to 
```
    val resources = getClass.getClassLoader.getResources(from)
    var res: InputStream = null
    var done = false
    while (resources.hasMoreElements && !done) {
      val next = resources.nextElement()
      if (next.getPath.contains("scalameter")) {
        res = next.openStream()
        done = true
      }
    }
```

I guess there would be a more elegant way of doing this, although it works. If you would like to make a PR with this, let me know.

**Comment by axel22** [comment]
I'd say that this looks good already - please feel free to send in a PR.
