### ISSUE TITLE
Sample code on home page is deprecated

### ISSUE THREAD

**Issue by byoungs** [scalameter/scalameter#185]
```extends PerformanceTest.Microbenchmark {```

should probably change to:

```object RangeBenchmark extends Bench.ForkedTime {```

**Comment by axel22** [comment]
Yes, that code is outdated, thanks for noticing! Would you perhaps care to submit a PR?

Thanks,
Alex

On June 9, 2017 7:55:07 PM GMT+02:00, Brian Youngs <notifications@github.com> wrote:
>```extends PerformanceTest.Microbenchmark {```
>
>should probably change to:
>
>```object RangeBenchmark extends Bench.ForkedTime {```
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/scalameter/scalameter/issues/185

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by byoungs** [comment]
done. Submitted to website repo.

**Comment by axel22** [comment]
Thanks a lot!
