### ISSUE TITLE
Measure blocking in code

### ISSUE THREAD

**Issue by vooolll** [scalameter/scalameter#186]
Is there a way to measure with scalameter for how much time thread stays blocked in block of code?

**Comment by axel22** [comment]
Yes, there are several ways.

If you want to do this directly from your code, you should use inline benchmarking: https://scalameter.github.io/home/gettingstarted/0.5/inline/

If you want to do this from a test-like benchmark, you will need to write a custom measurer that captures the time spend in exactly your thread:

https://scalameter.github.io/home/gettingstarted/0.5/executors/index.html

https://github.com/scalameter/scalameter/blob/master/scalameter-core/src/main/scala/org/scalameter/Measurer.scala

Depending on how long it stays there, you might have precision problems - current `Measurer`s use `System.nanoTime`, so I guess microsecond-level measurements are at the lower end of what it makes sense to measure.
