### ISSUE TITLE
Deploy scalameter for Scala 2.12.x

### ISSUE THREAD

**Issue by mdedetrich** [scalameter/scalameter#187]
Scalameter currently is not built and deployed for Scala 2.12.x which causes issues in projects which  build for Scala 2.12.x

**Comment by bertrandkang** [comment]
There is this build for 2.12: https://mvnrepository.com/artifact/com.storm-enroute/scalameter_2.12/0.8.2

**Comment by mdedetrich** [comment]
Ah didn't notice (p.s. the documentation on the main site should probably be updated https://scalameter.github.io/)
