### ISSUE TITLE
Tracking upstream issue for missing casbah jars on maven central

### ISSUE THREAD

**Issue by bbarker** [scalameter/scalameter#191]
see https://groups.google.com/forum/#!topic/mongodb-casbah-users/G7MFCsEUvrU

**Comment by bbarker** [comment]
An alternative solution to this, based on the message posted by Ross Lawley, seems to be to use the new [mongo-scala-driver[(http://mongodb.github.io/mongo-scala-driver/) rather than casbah, which is deprecated. Alternatively, casbash seems to use a fat jar if we can figure out how to use that now (still not sure why the old jars are missing, since presumably this worked for people in the past).

**Comment by bbarker** [comment]
@axel22 I can take a look at trying the new mongo scala driver, but it does not support Scala 2.10, so support for 2.10 would have to be dropped (or the mongo support would have to be moved to a separate subproject, which doesn't really seem worth it since this will always live in testing scope).

**Comment by axel22** [comment]
I think that dropping 2.10 would be ok, since 2.10 users could always use and old ScalaMeter version.

**Comment by bbarker** [comment]
OK, sounds good. Looks like (according to scalameter's travis) only 2.11 is currently failing right now, rather odd - at least that means you are right re: users of 2.10 (I had the issue even when trying to use scalameter in a 2.11 project).

**Comment by bbarker** [comment]
Do you think it would be possible to publish a new maven artifact, when you have a chance, as well? The latest version I can't use in my large 2.11 project due to this issue, but, I can try publishing locally in the mean time (so no immediate rush while I'm getting up to speed with using ScalaMeter (haha..)).

**Comment by axel22** [comment]
Sure: https://oss.sonatype.org/service/local/repositories/releases/content/com/storm-enroute/scalameter_2.11/0.9/scalameter_2.11-0.9.jar
