### ISSUE TITLE
publish for Scala 2.13.0-M3?

### ISSUE THREAD

**Issue by SethTisue** [scalameter/scalameter#196]
this came up at https://github.com/mdedetrich/scalajson/pull/49

**Comment by fyodorovski** [comment]
It seems that, until scala-jackson-module and mongo db drivers update to 2.13, the scalameter 2.13 build might not work entirely correctly.

**Comment by cantor-chron** [comment]
The 0.10-SNAPSHOT version should be now available on Sonatype.
