### ISSUE TITLE
Cannot recognize classloader (not URLClassLoader): jdk.internal.loader.ClassLoaders$AppClassLoader@4b85612c

### ISSUE THREAD

**Issue by Christewart** [scalameter/scalameter#219]
It appears that scalameter fails to run on jdk11 

https://travis-ci.org/bitcoin-s/bitcoin-s/jobs/573849928#L2877

**Comment by MikeEngUSA** [comment]
Hi @axel22 !

Thanks for your hard work on this excellent project!

I'm using JDK 11, and could really use this fix. Do you have any plans for making another release? Any idea when that might be?

Mike
