### ISSUE TITLE
MatchError for scaledTimeSpan in scalatest

### ISSUE THREAD

**Issue by kpbochenek** [scalameter/scalameter#222]
I have 'scalatest' as my test framework and want to use 'scalameter' to periodically run benchmark tests.
In my build.sbt I have:
```scala
Test / testOptions += Tests.Argument("-F", sys.props.getOrElse("F", "1.0"))
```

When I try to execute scalameter test from console:

```bash
sbt "testOnly scredis.ClientBenchmark"
```

I get exception:
```stacktrace
[error] Uncaught exception when running scredis.ClientBenchmark: scala.MatchError: ((-~F)~1.0) (of class scala.util.parsing.combinator.Parsers$$tilde)
[error] sbt.ForkMain$ForkError: scala.MatchError: ((-~F)~1.0) (of class scala.util.parsing.combinator.Parsers$$tilde)
[error]         at org.scalameter.Main$Configuration$.$anonfun$fromCommandLineArgs$23(Main.scala:54)
[error]         at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:140)
[error]         at scala.util.parsing.combinator.Parsers$Success.map(Parsers.scala:139)
...
```

When this argument "-F" is removed scalameter benchmarks are executed properly.

**Comment by axel22** [comment]
As far as I understand, the unfortunate problem with sbt is that the test arguments are passed to all the test frameworks in the project.
I wonder if there's a way to override this in sbt.

**Comment by kpbochenek** [comment]
@axel22 good idea! I did not dig deeper into sbt, but turns out you can actually specify for which framework those arguments are :D 

Simply providing it as a first argument is enough:
```sbt
Test / testOptions += Tests.Argument(TestFrameworks.ScalaTest, "-F", sys.props.getOrElse("F", "1.0"))
```

Thanks for help :+1:
