### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by Facsimiler** [scalameter/scalameter#225]
Hi! It's been some time since a release was made for this project, over a year now.

In particular, the current release still doesn't support Java 9+ in a forked JVM (#219), even though that was fixed back in May.

Do you need any assistance getting the next release out? Let me know...

**Comment by axel22** [comment]
Thanks for the ping, and sorry for being dormant. I'll try to do it today.

**Comment by ColOfAbRiX** [comment]
We really need a new release

**Comment by fyodorovski** [comment]
I did the new release now - it is on Sonatype, and should be synced to Maven in the next hours.

Btw, it might be a good idea to move the artifact to a different org, and have someone from the community do the releases from now on if they are needed on a more frequent basis.

**Comment by Facsimiler** [comment]
Thanks, @fyodorovski! I really appreciate that! I'll check it out shortly...
