### ISSUE TITLE
Remove mongo dependency and make a release

### ISSUE THREAD

**Issue by MrPowers** [scalameter/scalameter#229]
Thank you for building this great project!

Can we remove [the mongo dependency](https://github.com/scalameter/scalameter/blob/318a4de8c3ba9375198d2b047e513ff4a3dbbc58/project/Build.scala#L130) from the Scala 2.12 and Scala 2.11 builds and make a release?

I don't think mongo is being used anywhere in the project so I think you can just delete the dependency and make a release (for Scala 2.11, Scala 2.12, and Scala 2.13).

Thanks again for building this project and making it open source!

**Comment by fyodorovski** [comment]
Yes, it's removed, I'm preparing the release now.
