### ISSUE TITLE
Idea: use verbose mode by default

### ISSUE THREAD

**Issue by DarkDimius** [scalameter/scalameter#39]
I find myself always adding --verbose argument.
It seems reasonable to always Emmit log, as It's not that big and often contains valuable information.

Maybe verbose mode should be the default one, and instead there should be --quiet flag, that disables it?

**Comment by satybald** [comment]
Could someone tell how would be possible to get rid of "GC detected" messages?

I configured in build.sbt following "-silent" flag but still have this message.
```

libraryDependencies += "com.storm-enroute" %% "scalameter-core" % "0.6"


val scalaMeterFramework = new TestFramework("org.scalameter.ScalaMeterFramework")

testFrameworks in ThisBuild += scalaMeterFramework

testOptions in ThisBuild += Tests.Argument(scalaMeterFramework, "-silent")
```

**Comment by satybald** [comment]
BTW I'm doing inline benchmarks

**Comment by axel22** [comment]
Use ScalaMeter 0.7 - I believe you should not be seeing it. If you are, then this is a bug.
