### ISSUE TITLE
Measured time extrapolation

### ISSUE THREAD

**Issue by Fristi** [scalameter/scalameter#89]
Thanks for this excellent library.

I am wondering if it is possible to extrapolate the measured execution time as my set size increases. It would be nice to 'assert' if a function performs in (near) constant time or linear time in code.

**Comment by iphydf** [comment]
I agree this feature would be nice to have. The library would probably fail if better. Right now, the regression tests work both ways: if the new run is better than the old one, it still fails.

**Comment by axel22** [comment]
This could be easy to implement using a custom `Reporter` (easy in the sense that it would require least amount of fiddling with ScalaMeter infrastructure, and the focus would be purely on the functionality). By specifying a custom reporter, and a config option for the expected extrapolation, one could do something like the following:

    override def reporter = new ExtrapolationReporter
    
    performance of "foo" config(
      exec.extrapolation -> "linear"
    ) in {
      ...
    }

Eventually, I might tackle it, although I'm a little low on bandwidth right now. If somebody would like to submit a patch, I'd be happy to merge such a functionality.
