### ISSUE TITLE
[feature request]/[question] is there a simple way to perform tests along multiple dimensions?

### ISSUE THREAD

**Issue by makoConstruct** [scalameter/scalameter#95]
I'm trying to test something for which there are multiple variables that affect the performance of the algorithm. Is scalameter set up to make it easy to do this? Like, could I do it with a generator that generates generators that close over variously configured data structures, which then generate input for those data structures, and produce three-axis data from that, with axes labelled ~"configuration", "input size", "performance"?

**Comment by axel22** [comment]
Yes, see for-comprehensions on generators:

http://scalameter.github.io/home/gettingstarted/0.7/generators/index.html

Also, here is an example where there are multiple input axes:

https://github.com/scala-blitz/scala-blitz/blob/master/src/test/scala/org/scala/optimized/test/scalameter/Generators.scala#L75

Here is the kind of output such generators produce:

http://bit.ly/1yYyq8I

There are currently no 3D plots produced, but the above is an
interactive 2D plot in which you can drag the parallelism, date, or
size bars up and down - whichever bar is on the top will be the axis
for the plot.

**Comment by makoConstruct** [comment]
Cool.

But ![I'm not seeing what you describe](https://cloud.githubusercontent.com/assets/346569/5990972/f4381ef0-aa33-11e4-87c4-fd9154c73b90.png) in the link about the output, there's certainly no raw output being displayed. And it doesn't seem to be possible to get more than three data points per curve onto the graph.

**Comment by axel22** [comment]
Not sure what you mean by raw output, but every benchmark outputs:
- standard output
- a json file with all the data points
- a binary history file with records about previous runs
These are not currently shown in the graph, no.

The reason that there are only 3 data points on this particular graph is that the `Par[Range].aggregate.Par` benchmark has a generator that outputs only 3 size points (to prevent the benchmark suite from running to long). If you configure the generator for more points, you will be able to receive more. The size axis shows all the data points from all the benchmarks - this could be made more intuitive by showing (or enabling) only the datapoints of the currently selected curves.

**Comment by makoConstruct** [comment]
Ah right.
How do you get Json output? The html report you linked to uses the dsv output format, which seems less than ideal, especially considering that the any third axis(and presumably fourth and fifth as well) inputs(Parallelization factor, in this case) apparently only get recorded in dsv the file name, rather than in the data itself. That is a bit of an awkward format.

**Comment by axel22** [comment]
Not sure what you mean by "third axis being recorded in the file name". The dsv output format contains the third (and fourth, and so on) axis only if the measurement was done using a generator with multiple axes. Here is one such example:

http://chara.epfl.ch/~prokopec/npc-i7/Par%5BArray%5D.filter%28mod3%29.Par.dsv

JSON should be available if you select the `embedDsv` option on a `HtmlReporter` to `true`:

https://github.com/scalameter/scalameter/blob/master/src/main/scala/org/scalameter/reporting/HtmlReporter.scala

Not sure right now if it produces a separate JSON file, but you could either tweak the HtmlReporter to produce a separate JSON file, or implement your own reporter that produces a JSON file. If you do, a pull request is welcome :)

**Comment by makoConstruct** [comment]
Heh, apologies, I was confused by the presence of such files in http://chara.epfl.ch/~prokopec/npc-i7/ , I see now that it doesn't include any of them in data.js.

That answers my question. Thank you.

**Comment by axel22** [comment]
Good to hear that - you're welcome! :)
